<script src="https://static-dev.gamiphy.co/sdk/loyalty-station/main.js"></script>
<script>
    window.gamiphyAsyncInit = function () {
        window.LoyaltyStation.init({
            app: "<?php echo $block->getAppId() ?>",
            <?php
            if ($this->customerSession->isLoggedIn()) {
                echo "user: " . json_encode($block->getUser());
            }
            ?>
        });
    };
</script>
